version: '3.9'
services:
  react-tutorial:
    stdin_open: true
    build: 
      context: .
      dockerfile: Dockerfile.local
    ports:
      - 9999:3000
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
  test:
    build: 
      context: .
      dockerfile: Dockerfile.local
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
    command: ['yarn', 'test']
