name: Build and Deploy to GKE

on:
  push:
    branches: [ trunk ]
env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT_DEV }}
  GKE_CLUSTER: react-tutorial-staging
  GKE_ZONE: asia-northeast1
  DEPLOYMENT_NAME: react-tutorial
  IMAGE: react-tutorial

jobs:
  build_publish_deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup gcloud cli
        uses: google-github-actions/setup-gcloud@v0.3.0
        with:
          service_account_key: ${{ secrets.GKE_SA_KEY_DEV }}
          project_id: ${{ secrets.GKE_PROJECT_DEV }}

      - name: Configure Docker to use gcloud cli as auth helper
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get GKE credentials
        uses: google-github-actions/get-gke-credentials@v0.5.0
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ secrets.GKE_SA_KEY_DEV }}

      - name: Build and Test
        run: |-
          docker build \
            -t "${{ github.repository_owner }}/$IMAGE:$GITHUB_SHA" \
            ./
      
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Publish
        run: |-
          docker image push ghcr.io/${{ github.repository_owner }}/${IMAGE}:${GITHUB_SHA}
          docker image push ghcr.io/${{ github.repository_owner }}/${IMAGE}:latest

      - name: Deploy to GKE cluster
        run: |-
          helm upgrade --install --values=./helm/staging-values.yml ${DEPLOYMENT_NAME} ./helm
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          kubectl get services -o wide
