name: hook push

on:
  push:
    branches: [ develop, main ]

env:
  IMAGE: react-tutorial

jobs:
  sample:
    name: sample
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build image for test
        run: |-
          docker build --target build --tag $IMAGE:test .

      - name: Run Test
        run: |-
          docker run $IMAGE:test yarn test --watchAll=false
